# Tanks and Temples dataset
dataset: nsvf
image_batching: false
factor: 0
num_coarse_samples: 64
num_fine_samples: 128
use_viewdirs: false
white_bkgd: true  # No alpha channel
batch_size: 1024
randomized: true
sh_deg: 4
max_steps: 2000000
near: 0.0
far: 4.0
sparsity_radius: 5.0
sparsity_length: 0.2
